# Scenarios are defined by parameter *name* (order-independent).
# The canonical parameter list + UI order is in parameters.yaml.
# Any missing parameter can be filled by GUI defaults; extra keys should be treated as an error.

CycloneBaseZhang:
  t0: 0
  tc: -1
  tt: -1
  tmax: 60
  Np: 50000
  Nc: 100
  Nloop: 2
  Nreal: 1
  Nt: 1200
  ntraj: 10
  Ti: 0.5
  Te: 0.5
  Zeff: 1.0
  Aeff: 1.0
  ndens: 4.5
  Ln: 2.2
  Li: 2.2
  Le: 6.9
  magnetic_model: 4
  B0: 1.9
  R0: 1.71
  a0: 0.625
  safe1: 0.85
  safe2: 0.0
  safe3: 2.2
  amp: 1.0
  elong: 1.2
  device: 3
  shot: 54178
  shotslice: 6
  Omgt0: 0
  Omgtprim: 0
  Phi: 0.011
  turbprof: 5.0
  Ai: 1.0
  lambdax: 5.0
  lambday: 5.0
  lambdaz: 1000.0
  lbalonz: 1000.0
  tauc: 10.0
  k0i: 0.05
  k0e: 0.05
  gamma_ZF: 0.0
  X0: 2.022
  Y0: 0.0
  Z0: 0
  Tw: 1.0
  Ew: 1.0
  pitch: 0.3
  Aw: 1.0
  Zw: 1.0
  position_type: 2
  pitch_type: 2
  energy_type: 2
  USE_larmor: 1
  USE_coll: 0
  USE_turb: 1
  USE_magnturb: 0
  USE_freq: 1
  USE_polar: 0
  USE_PC: 0
  USE_real: 0
  USE_corr: 0
  USE_balloon: 0
  USE_tilt: 1
  USE_testing: 0

MAST-U:
  t0: 0
  tc: -1
  tt: -1
  tmax: 100
  Np: 20000
  Nc: 100
  Nloop: 1
  Nreal: 1
  Nt: 1000
  ntraj: 10
  Ti: 0.45
  Te: 0.35
  Zeff: 2.0
  Aeff: 2.0
  ndens: 3.4
  Ln: 2.2
  Li: 2
  Le: 3
  magnetic_model: 2
  B0: 0.7
  R0: 0.9
  a0: 0.47
  safe1: 1.0
  safe2: 0.0
  safe3: 5.0
  amp: 1.1
  elong: 1.2
  device: 1
  shot: 47090
  shotslice: 600
  Omgt0: 50
  Omgtprim: 0
  Phi: 0.04
  turbprof: 5.0
  Ai: 0.8
  lambdax: 5.0
  lambday: 5.0
  lambdaz: 1.0
  lbalonz: 1000.0
  tauc: 10.0
  k0i: 0.1
  k0e: 0.1
  gamma_ZF: 0.0
  X0: 1.2
  Y0: 0
  Z0: 0
  Tw: 1.0
  Ew: 1.0
  pitch: 0.0
  Aw: 2.0
  Zw: 1.0
  position_type: 2
  pitch_type: 2
  energy_type: 2
  USE_larmor: 1
  USE_coll: 0
  USE_turb: 1
  USE_magnturb: 0
  USE_freq: 1
  USE_polar: 0
  USE_PC: 0
  USE_real: 0
  USE_corr: 0
  USE_balloon: 0
  USE_tilt: 1
  USE_testing: 0

TCV:
  t0: 0
  tc: -1
  tt: -1
  tmax: 100
  Np: 200000
  Nc: 100
  Nloop: 1
  Nreal: 1
  Nt: 2000
  ntraj: 10
  Ti: 0.5
  Te: 5.0
  Zeff: 2.0
  Aeff: 2.0
  ndens: 1.0
  Ln: 7
  Li: 7
  Le: 7
  magnetic_model: 2
  B0: 0.7
  R0: 0.9
  a0: 0.47
  safe1: 1.0
  safe2: 0.0
  safe3: 5.0
  amp: 1.1
  elong: 1.2
  device: 2
  shot: 81500
  shotslice: 2
  Omgt0: 0.0
  Omgtprim: 0.0
  Phi: 0.005
  turbprof: 5.0
  Ai: 0.0
  lambdax: 5.0
  lambday: 5.0
  lambdaz: 2.0
  lbalonz: 1000.0
  tauc: 50.0
  k0i: 0.1
  k0e: 0.1
  gamma_ZF: 0.0
  X0: 1.03
  Y0: 0
  Z0: 0
  Tw: 1.0
  Ew: 1.0
  pitch: 0.0
  Aw: 2.0
  Zw: 1.0
  position_type: 2
  pitch_type: 2
  energy_type: 2
  USE_larmor: 1
  USE_coll: 0
  USE_turb: 1
  USE_magnturb: 0
  USE_freq: 1
  USE_polar: 0
  USE_PC: 0
  USE_real: 0
  USE_corr: 0
  USE_balloon: 0
  USE_tilt: 1
  USE_testing: 0

WEST:
  t0: 0
  tc: -1
  tt: -1
  tmax: 60
  Np: 10000
  Nc: 100
  Nloop: 1
  Nreal: 1
  Nt: 1500
  ntraj: 10
  Ti: 0.8
  Te: 1.5
  Zeff: 2.0
  Aeff: 2.0
  ndens: 7.0
  Ln: 2.2
  Li: 6.0
  Le: 6.0
  magnetic_model: 2
  B0: 3.7
  R0: 2.5
  a0: 0.5
  safe1: 1.0
  safe2: 0.0
  safe3: 3.0
  amp: 1.0
  elong: 1.2
  device: 3
  shot: 54178
  shotslice: 6
  Omgt0: 0
  Omgtprim: 0
  Phi: 0.002
  turbprof: 5.0
  Ai: 0.99
  lambdax: 5.0
  lambday: 5.0
  lambdaz: 1.0
  lbalonz: 1000.0
  tauc: 30.0
  k0i: 0.1
  k0e: 0.1
  gamma_ZF: 0.0
  X0: 2.75
  Y0: 0
  Z0: 0
  Tw: 1.0
  Ew: 0.001
  pitch: 0.4
  Aw: 1.0
  Zw: 1.0
  position_type: 2
  pitch_type: 2
  energy_type: 2
  USE_larmor: 1
  USE_coll: 0
  USE_turb: 1
  USE_magnturb: 0
  USE_freq: 1
  USE_polar: 0
  USE_PC: 0
  USE_real: 0
  USE_corr: 0
  USE_balloon: 0
  USE_tilt: 1
  USE_testing: 0

CycloneBaseCase:
  t0: 0
  tc: -1
  tt: -1
  tmax: 60
  Np: 50000
  Nc: 100
  Nloop: 1
  Nreal: 1
  Nt: 1200
  ntraj: 10
  Ti: 3.0
  Te: 3.0
  Zeff: 1.0
  Aeff: 1.0
  ndens: 5.0
  Ln: 2.2
  Li: 6.9
  Le: 6.9
  magnetic_model: 4
  B0: 2.2
  R0: 1.65
  a0: 0.600
  safe1: 0.84
  safe2: 0.0
  safe3: 2.24
  amp: 1.0
  elong: 1.2
  device: 3
  shot: 54178
  shotslice: 6
  Omgt0: 0
  Omgtprim: 0
  Phi: 0.05
  turbprof: 5.0
  Ai: 1.0
  lambdax: 5.0
  lambday: 5.0
  lambdaz: 1.0
  lbalonz: 1.0
  tauc: 10.0
  k0i: 0.05
  k0e: 0.05
  gamma_ZF: 0.0
  X0: 1.95
  Y0: 0
  Z0: 0
  Tw: 1.0
  Ew: 1.0e-01
  pitch: 0.4
  Aw: 1.0
  Zw: 1.0
  position_type: 2
  pitch_type: 2
  energy_type: 2
  USE_larmor: 1
  USE_coll: 0
  USE_turb: 1
  USE_magnturb: 0
  USE_freq: 1
  USE_polar: 0
  USE_PC: 0
  USE_real: 0
  USE_corr: 0
  USE_balloon: 1
  USE_tilt: 1
  USE_testing: 0

Personal scenario: {}

